---
- name: Checkout gist file from github
  git:
    repo: https://gist.github.com/pensierinmusica/6206493
    dest: /home/ubuntu/gist
- name: Move gist file to sysctl.d/ directory
  command:
    cmd: mv network-tuning.conf /etc/sysctl.d/
    chdir: /home/ubuntu/gist
- name: Remove gist directory
  command:
    cmd: rm -rf gist/
    chdir: /home/ubuntu/
- name: Configure new kernel parameters
  command:
    cmd: sysctl -e -p /etc/sysctl.d/network-tuning.conf

