---
- name: Checkout gist file from github
  git:
    repo: "{{ repo_url }}"
    dest: "{{ home_dir }}{{ gist_dir }}"
- name: Move gist file to sysctl.d/ directory
  command:
    cmd: mv "{{ conf_file }}" "{{ sysctl_dir }}"
    chdir: "{{ home_dir }}{{ gist_dir }}"
- name: Remove gist directory
  command:
    cmd: rm -rf "{{ gist_dir }}"
    chdir: "{{ home_dir }}"
- name: Configure new kernel parameters
  command:
    cmd: sysctl -e -p "{{ sysctl_dir }}{{ conf_file }}"

