---
- hosts: all
  become: yes
  tasks:
  - name: Install pip
    apt:
      name: python3-pip
      state: latest
  - name: Install python docker module
    pip:
      name: docker
  - name: Nginx docker container
    docker_container:
      name: nginx
      image: nginx
      state: started
      exposed:
        - 80
